server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: service-ribbon